version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_OPENROUTER_API_KEY=${VITE_OPENROUTER_API_KEY}
      - VITE_OPENROUTER_API_URL=${VITE_OPENROUTER_API_URL}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_STEP_API_KEY=${VITE_STEP_API_KEY}
      - VITE_STEP_API_URL=${VITE_STEP_API_URL}
    volumes:
      - ./dist:/app/dist
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 3s
      retries: 3